### ISSUE TITLE
Better datetime picker

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/platypub#10]
![image](https://user-images.githubusercontent.com/3696602/174414720-1e12570d-7a27-4617-a008-8e7d8e64308b.png)

Once again there's [a native component](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) I had no idea existed.

**Comment by mathushabai** [comment]
Hi, what's your preferred format for the datetime picker?

**Comment by jacobobryant** [comment]
I don't have any strong preferences. We just need to be able to populate the [publish date](https://github.com/jacobobryant/platypub/blob/master/src/com/platypub/schema.clj#L22) attribute and have it be nicer to use than the current plain text field. The native component linked above looks alright to me. Or we could do separate components like Ghost does:

![image](https://user-images.githubusercontent.com/3696602/174452657-ab030db9-19f7-4727-a738-a62a83b7be47.png)
![image](https://user-images.githubusercontent.com/3696602/174452671-6de3570d-5930-4eb3-8f32-1d5bc2a3fd8a.png)

We'll need to account for timezone somehow--I see Ghost does this by just using UTC for the time field. That could be OK, or we could have an additional timezone field that gets auto-populated on the client side.

It might be worth taking a look at drop-in javascript components, maybe there's something that'd be better than the native component.

**Comment by CodeWithUmair** [comment]
Hello! @jacobobryant I'm interested in learning more about your problem, so please provide additional information.

**Comment by jacobobryant** [comment]
@CodeWithUmair what additional information would be helpful? Have you been able to run Platypub locally? If so you can go to the post edit page to see the current "Publish date" field.

**Comment by jacobobryant** [comment]
1 sounds good to me. In the Ghost screenshot above they just put a `(UTC)` in the time field.

I'm not sure if 2 or 3 would be best as a next step or if it'd be better to look for a drop-in js component that handles time zone (perhaps by defaulting to browser's time zone but allowing an override). In any case, we can close this issue after 1 is done and then wait a bit to see if it feels worthwhile to do something fancier--maybe UTC will be good enough.

**Comment by MTrost** [comment]
Thanks for the reply, I plan on working on this Friday afternoon (European time) or Saturday and will try it out with two input fields.

(and sorry for more or less asking the questions you already answered in the comment above: Somehow I only read the text above the pictures...)

**Comment by jacobobryant** [comment]
Sounds great! And no worries 🙂

**Comment by MTrost** [comment]
So over 2 months later I finally opened a PR for this 😄
