### ISSUE TITLE
Set max width on images within TinyMCE

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/platypub#17]
The grumpycat picture in https://github.com/jacobobryant/platypub/issues/14 reminded me that images in the editor are displayed at full width. Better if we make them shrink so they don't overflow on the x axis.

**Comment by jeffp42ker** [comment]
I've been manually re-sizing images to 800 or 1024 pixel-width prior to upload.  I'd be nice to skip that step if upload-image could handle that step.

**Comment by jacobobryant** [comment]
Hm, that should be doable... I've made a second issue for this: https://github.com/jacobobryant/platypub/issues/23

**Comment by jacobobryant** [comment]
(for this issue I'm basically just thinking about setting `style="max-width:..."` on image elements inside TinyMCE; I'm hoping TinyMCE has an option for that we can flip on)
