### ISSUE TITLE
Replace shell calls like `cp -r` with more jvm-y alternatives

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/platypub#22]
I have shell calls to `rm`, `cp` and `chmod` in various places due to sheer laziness. I'm not sure if this will actually be a problem, but it wouldn't hurt to replace them with the JVM's filesystem capabilities. Maybe use [babashka/fs](https://github.com/babashka/fs).

**Comment by bhlieberman** [comment]
I'd be willing to tackle this and some of the other first issue tags. A regular PR would be okay? Or do you prefer it some other way?

**Comment by jacobobryant** [comment]
Regular PR would be great--thanks!

**Comment by jacobobryant** [comment]
Let me know if you run into any issues/have any questions.

**Comment by jacobobryant** [comment]
Closed by #75
