### ISSUE TITLE
Slug value generated from post title would be helpful

### ISSUE THREAD

**Issue by jeffp42ker** [jacobobryant/platypub#26]
When creating a post's slug I typically:

- copy-paste the title
- lower-case the words
- remove apostrophes, special characters
- replace spaces with dashes
- add a date representation to ensure it's unique

It'd be helpful if this transformation was available as the candidate slug value once the title is completed.

**Comment by jacobobryant** [comment]
Good idea. For ease of implementation, maybe a good first step would be to do it on document save? i.e. if the title is non-empty and the slug is empty, then infer the slug and save it to the document. Then it'd also be easy to query the db to ensure the slug is unique without needing to add a date or similar.
