### ISSUE TITLE
Custom schema for posts

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/platypub#41]
We already support custom schema for sites. After #39 is closed, do the same for posts. See https://github.com/jacobobryant/platypub/blob/master/themes/default/custom-schema.edn. Grep for `custom-schema.edn` to see the places that sites' custom schema is already used and mirror that for posts.

**Comment by jeffp42ker** [comment]
What sort of relationship should we implement between post and site custom schema?

We could have a post value override a site value, it being more local.

Navigation links in particular seems like an attribute that should remain at the site level.

We could maintain separate custom schema maps and construct override rules for attributes they have in common.

**Comment by jacobobryant** [comment]
> What sort of relationship should we implement between post and site custom schema?
> ...
> Should a post value override a site value, since it's more local?

I was imagining they'd be separate; no need for post values to override site values. i.e. currently we have a `:site/custom-config` attribute for sites. We could add a `:post/custom-config` attribute.

I guess there could be overrides, but it would happen within the theme code. e.g. maybe a site has a custom attribute for author, but posts also have a custom author attribute. As the theme writer you'd probably make it so that posts use their own author value first but default to the site author if one isn't defined. But Platypub itself wouldn't need to be aware of that.

> Can custom schema attributes remain optional, i.e. assigning no value means no key?

I think either way is fine. Looks like for `:site/custom-config` we still add the key put use an empty string for the value (https://github.com/jacobobryant/platypub/blob/master/src/com/platypub/feat/sites.clj#L34). We could have it remove the key altogether instead and make sure that themes don't break when their custom config values are nil. (I don't know off the top of my head if the default theme has problems with that currently--I don't think it does?)

> Should separate custom schema maps be maintained and override rules constructed for attributes they have in common?

Originally my thought was that if a theme defines any new custom schema, it is the owner for those keys (and the keys should be namespaced accordingly, e.g. :com.platypub/primary-color etc.) With the current site custom config thing, I'd say if you wanted to make a new theme that reused the existing :com.platypub/* keys, you'd copy platypub's custom config and not make any changes. (of course at this point all custom config values are of type string, so it's not like there's much to override anyway.)

However I'm beginning to think that before we implement any post custom schema stuff, maybe we should figure out exactly how item types (#43) are going to work, and then implement item types + custom post schema all at once. Otherwise I'd be afraid of implementing something that we're just going to change anyway.

**Comment by jeffp42ker** [comment]
Yes, event attributes are what I'm considering as additional item fields which will include three of instant types.

**Comment by jeffp42ker** [comment]
The author attributes are a good fit for customizing in posts. At the theme level perhaps they can be moved to a `custom-post-schema.edn` file and set the main author in defaults.

**Comment by jacobobryant** [comment]
Sounds reasonable--I'm planning to put some thinkin' into a possible implementation this friday, so hopefully I'll have a concrete implementation we can poke holes in soon.
