### ISSUE TITLE
Better color picker component

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/platypub#8]
Currently we're just using a text field:

![image](https://user-images.githubusercontent.com/3696602/174414310-02b80c18-57c7-4254-8d19-7b8d317abcdf.png)

After searching for "javascript color picker component" I see that `<input type="color">` is a thing?! (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color). That might be a good option. Either that or some drop-in component like [jscolor](https://jscolor.com/).

**Comment by jeffp42ker** [comment]
This tool provides color advice for cartography: https://colorbrewer2.org/

It might be useful in picking colors for a theme too.

**Comment by jacobobryant** [comment]
Hm could be--this could be a good fit for a "Resources for theme developers" section, perhaps in the README.

**Comment by joerter** [comment]
<img width="685" alt="Screenshot 2023-02-21 at 9 57 42 PM" src="https://user-images.githubusercontent.com/5200724/220510033-50d2c828-3f3c-4494-8a37-5345b7c698fa.png">

How's something like this look? It's an `input[color]` on the left and the normal text input on the right. I'm thinking they could be 2 way bound so an update in either updates the other.

**Comment by jacobobryant** [comment]
That looks good to me. Too bad the native color component doesn't just come with hex input... Anyway, I think you could do the data binding with a couple of hyperscript one liners, something like `:_ "on change set #text-input's value to my value"` and vice versa (that may or may not be the right syntax).
